import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,User,publicDemo} from './client';
import Workspace from './Workspace';
import PublicDemo from './PublicDemo';
import {product} from './product';
import './style.css';

interface Audit { id:string; action:string; resource:string; outcome:string; actor:string; created:number }
function App(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[view,setView]=useState('workspace');
 const [email,setEmail]=useState('admin@alpha.test'),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [audit,setAudit]=useState<Audit[]>([]);
 useEffect(()=>{api<User>('/me').then(setUser).catch(()=>{}).finally(()=>setLoading(false));},[]);
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{setUser(await api<User>('/login','POST',{email,password}));setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function navigate(next:string){setView(next);setError('');if(next==='audit'){try{setAudit(await api<Audit[]>('/audit'));}catch(e){setError((e as Error).message);}}}
 if(loading)return <div className="loading">Opening secure workspace…</div>;
 if(!user)return <main className="login-layout"><section className="login-story"><div className="wordmark"><span className="logo">{product.mark}</span>{product.name}<small> / SECURE AI</small></div><div className="story-body"><p className="eyebrow">ENGINEERED FOR TRUST</p><h1>{product.headline}</h1><p className="lede">{product.description}</p><div className="story-grid">{product.features.map((f,i)=><div key={f}><span>0{i+1}</span><h3>{f}</h3></div>)}</div></div><footer>Built by Yeabsira Mesfin <span>Python · React · Security engineering</span></footer></section><section className="login-form"><span className="pill">LOCAL DEMO WORKSPACE</span><h2>Welcome back.</h2><p>Sign in with an account created by the demo setup.</p><form onSubmit={signIn}><label>Account<select aria-label="Account" value={email} onChange={e=>setEmail(e.target.value)}>{['admin@alpha.test','analyst@alpha.test','viewer@alpha.test','reviewer@alpha.test','admin@beta.test'].map(a=><option key={a}>{a}</option>)}</select></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password from the seed command"/></label>{error&&<div role="alert" className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Open workspace →'}</button></form><div className="note"><strong>Try different permissions</strong><p>Alpha and Beta are separate organizations. A viewer can inspect authorized information; an administrator can manage it.</p></div></section></main>;
 return <div className="app"><aside className="sidebar"><div className="wordmark"><span className="logo">{product.mark}</span>{product.name}</div><div className="tenant-box"><span className="avatar">{user.tenant[0].toUpperCase()}</span><div><strong>{user.tenant.toUpperCase()} workspace</strong><small>Isolated organization</small></div></div><p className="nav-label">CONTROL CENTER</p><nav>{[['workspace',product.nav],['audit','Audit trail'],['guide','Project guide']].map(([id,label],i)=><button key={id} className={view===id?'active':''} onClick={()=>void navigate(id)}><span>{['◈','≡','◇'][i]}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="scope"><span className="status-dot"/> Session authenticated</div><strong>{user.email}</strong><small>{user.role} permissions</small><button className="text-button" onClick={async()=>{try{await api('/logout','POST');setUser(null);setView('workspace');}catch(e){setError((e as Error).message);}}}>Sign out ↗</button></div></aside><main className="main"><header className="topbar"><span>Portfolio lab <b>/</b> {product.name}</span><span className="pill">{user.role.toUpperCase()} ACCESS</span></header>{error&&<p role="alert" className="error">{error}</p>}{view==='workspace'?<Workspace user={user}/>:view==='audit'?<section className="page"><p className="eyebrow">ACCOUNTABILITY</p><h1>Every decision has a trail.</h1><p className="muted">Tenant-scoped events. No raw prompts, document content, or credentials are logged.</p><div className="panel table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Decision</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{new Date(a.created*1000).toLocaleTimeString()}</td><td><code>{a.action}</code></td><td>{a.actor}</td><td><span className="badge">{a.outcome}</span></td></tr>)}</tbody></table>{!audit.length&&<p className="empty">No events recorded yet.</p>}</div></section>:<section className="page"><p className="eyebrow">THE ENGINEERING</p><h1>{product.name}, under the hood.</h1><p className="lede">{product.description}</p><div className="cards">{product.features.map((f,i)=><article className="panel" key={f}><p className="eyebrow">CONTROL 0{i+1}</p><h2>{f}</h2><p>{product.details[i]}</p></article>)}</div><article className="panel"><h2>Demonstration boundaries</h2><p>{product.limitations}</p><p>Read the repository README and threat model for setup, test evidence, design decisions, and production hardening work.</p></article></section>}<footer className="main-footer">{product.name} <span>Secure AI portfolio / Yeabsira Mesfin</span></footer></main></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode>{publicDemo?<PublicDemo/>:<App/>}</React.StrictMode>);
