import {useState} from 'react';
import Workspace from './Workspace';
import {setDemoPersona, User} from './client';

export default function PublicDemo(){
 const [email,setEmail]=useState('admin@alpha.test');
 const user:User={id:email,email,tenant:email.includes('beta')?'beta':'alpha',role:email.startsWith('admin')?'admin':email.startsWith('analyst')?'analyst':'viewer'};
 return <div className="public-demo"><header className="demo-header"><a className="wordmark" href="/"><span className="logo">V</span>Vaultwise</a><a className="secondary" href="https://github.com/yeabsira-mesfin/vaultwise-secure-knowledge">View source ↗</a></header><main><section className="demo-intro"><p className="eyebrow">AI SECURITY / INTERACTIVE PORTFOLIO</p><h1>Explore knowledge.<br/>Respect the boundary.</h1><p>Ask a question, inspect the evidence, then change the sample role to see which sources remain available.</p><div className="demo-controls"><label>Sample persona<select value={email} onChange={e=>{setDemoPersona(e.target.value);setEmail(e.target.value);}}>{['admin@alpha.test','analyst@alpha.test','viewer@alpha.test','admin@beta.test'].map(value=><option key={value}>{value}</option>)}</select></label><p><strong>Public synthetic demo</strong><br/>No sign-in. No uploads or saved conversations. The persona selector demonstrates server-side retrieval filters; it is not authentication. Use sample questions only.</p></div></section><Workspace key={email} user={user}/><section className="demo-notes"><h2>Built for inspection.</h2><p>This demo runs the project’s Python retrieval and injection checks on a fresh sample corpus for each request. Answers quote matching documents; no paid model is called.</p><p>The full application includes session authentication, document ingestion, tenant-scoped audit logs, and optional local Ollama generation. Run it from the repository to test those features. Heuristic injection checks can miss attacks.</p><a href="https://github.com/yeabsira-mesfin/vaultwise-secure-knowledge#run-locally">Run the full application ↗</a></section></main><footer className="main-footer">Vaultwise <span>Built by Yeabsira Mesfin</span></footer></div>;
}
